#!/usr/bin/env bash
# Regenerates HELP.md from the offline `naru /help --full` manual.
#
# The command text itself cannot be a prompt: HELP.md must be stable and must not depend on
# a reasoning model. This script therefore drives the NaruHelpGenerateMain bootstrap, which
# builds a headless session, runs the `/help` directive, and prints its result. The output
# is fenced into a plain-text code block so the generated manual can sit inside Markdown
# without being re-interpreted by other tools.
#
# Requirements:
#   - JDK 25 on PATH (the same toolchain the reactor uses)
#   - the reactor artifacts resolvable from Maven (offline is the default; set
#     NARU_OFFLINE=0 to allow network resolution)
#
# Usage:
#   scripts/generate-help.sh [--full | --syntax | <directive> ...]
#     (defaults to --full)
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

: "${NARU_OFFLINE:=1}"
if [ "$#" -eq 0 ]; then
    set -- --full
fi

MAVEN_ARGS=(-q -pl app/naru)
if [ "$NARU_OFFLINE" = "1" ]; then
    MAVEN_ARGS+=(-o)
fi

echo "==> building the app and its dependencies" >&2
mvn "${MAVEN_ARGS[@]}" -am -DskipTests install

echo "==> resolving the runtime classpath" >&2
CP_FILE="$(mktemp)"
GENERATED="$(mktemp)"
trap 'rm -f "$CP_FILE" "$GENERATED"' EXIT
if [ "$NARU_OFFLINE" = "1" ]; then
    mvn "${MAVEN_ARGS[@]}" dependency:build-classpath -Dmdep.outputFile="$CP_FILE" -Dmdep.includeScope=runtime
else
    mvn -q -pl app/naru dependency:build-classpath -Dmdep.outputFile="$CP_FILE" -Dmdep.includeScope=runtime
fi
CP="app/naru/target/classes:$(cat "$CP_FILE")"

echo "==> generating /help $*" >&2
java -cp "$CP" net.thevpc.naru.NaruHelpGenerateMain "$@" > "$GENERATED"

echo "==> writing HELP.md ($(wc -l < "$GENERATED") lines)" >&2
{
    printf '<!-- GENERATED by scripts/generate-help.sh from `naru /help %s` -- do not edit by hand. -->\n' "$*"
    printf '```\n'
    cat "$GENERATED"
    printf '\n```\n'
} > HELP.md

echo "==> done: HELP.md" >&2